//! Recovery of a build's reflection schema, and the diff between two
//! recoveries.
//!
//! Nothing this module writes is ever committed. An extraction lands under the
//! gitignored `.cache/schema/<buildid>` directory and is regenerated by
//! every contributor and every continuous integration job from a server they
//! fetched themselves. The extractor is the artifact; its output is not.
//!
//! Beside the seven dumps sits `build.json`, which names the build the dumps
//! came from. It exists so that `schema list`, `schema diff` and the build
//! watcher can identify an extraction without reopening a 22 MB image.

pub mod descriptor;
pub mod diff;
pub mod metadata;
pub mod program;
pub mod proto;
pub mod strings;

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result, bail};

use crate::image::Image;
use crate::root::DevRoot;
use crate::ui::{Mark, Row, Ui};
use crate::{SchemaCommand, kfc};

/// The seven files an extraction writes.
pub const OUTPUTS: [&str; 7] = [
    "srv.schema.txt",
    "cli.schema.txt",
    "srv.proto.txt",
    "ui-events.txt",
    "descriptors.tsv",
    "strings.tsv",
    "programs.tsv",
];

/// The line ending every dump uses.
const EOL: &str = "\r\n";

/// Run one `schema` subcommand.
///
/// # Errors
///
/// Returns an error when a path refuses to resolve, an image refuses to parse,
/// or an output cannot be written.
pub fn run(command: &SchemaCommand, root: &DevRoot, ui: &Ui) -> Result<bool> {
    match command {
        SchemaCommand::Extract {
            build,
            server,
            client,
            force,
        } => extract(
            root,
            ui,
            build.as_deref(),
            server.as_deref(),
            client.as_deref(),
            *force,
        ),
        SchemaCommand::List => Ok(list(root, ui)),
        SchemaCommand::Diff { old, new } => diff::run(root, ui, old, new),
    }
}

/// Write every dump for one build.
fn extract(
    root: &DevRoot,
    ui: &Ui,
    build: Option<&str>,
    server: Option<&Path>,
    client: Option<&Path>,
    force: bool,
) -> Result<bool> {
    let (server_exe, build_id) = locate_server(root, build, server)?;
    if !server_exe.is_file() {
        bail!(
            "no server executable at {}. Run `cargo xtask server fetch` first.",
            server_exe.display()
        );
    }

    ui.section("schema extract");
    let image = Image::open(&server_exe)?;
    let target = root.schema_build_dir(&build_id)?;
    if target.exists() && !force {
        bail!(
            "{} already holds an extraction of build {build_id}. Pass --force to replace it.",
            target.display()
        );
    }
    std::fs::create_dir_all(&target).with_context(|| format!("creating {}", target.display()))?;

    ui.line(&format!("build {build_id}"));
    let fingerprint = image.fingerprint().map(|print| metadata::Fingerprint {
        guid_file_order: print.guid_file_order(),
        guid_pdb: print.pdb_guid(),
        age: print.age,
    });
    match &fingerprint {
        Some(print) => ui.line(&format!(
            "fingerprint {} age {}",
            print.guid_file_order, print.age
        )),
        None => ui.line("fingerprint unknown: the image carries no debug record"),
    }
    let revision = match kfc::read_beside(&server_exe) {
        Ok(found) => {
            ui.line(&format!("revision r{} from {}", found.number, found.branch));
            Some(metadata::Revision {
                number: found.number,
                branch: found.branch,
                stamp: found.stamp,
            })
        }
        Err(err) => {
            ui.line(&format!("revision unknown: {err}"));
            None
        }
    };

    let mut rows = Vec::new();
    let descriptors = descriptor::walk(&image);
    rows.push(write(
        &target,
        "srv.schema.txt",
        &schema_dump(&image, &descriptors),
    )?);
    rows.push(write(
        &target,
        "descriptors.tsv",
        &descriptor_table(&descriptors),
    )?);
    rows.push(write(
        &target,
        "ui-events.txt",
        &ui_events(&image, &descriptors),
    )?);
    rows.push(write(&target, "srv.proto.txt", &proto_dump(&image))?);
    rows.push(write(&target, "strings.tsv", &string_table(&image))?);
    rows.push(write(&target, "programs.tsv", &program_table(&image))?);

    match client {
        Some(path) => {
            let client_image = Image::open(path)?;
            let client_descriptors = descriptor::walk(&client_image);
            rows.push(write(
                &target,
                "cli.schema.txt",
                &schema_dump(&client_image, &client_descriptors),
            )?);
        }
        None => {
            rows.push(
                Row::new(Mark::Note, "cli.schema.txt", "skipped")
                    .note("pass --client <exe> to read the client build"),
            );
        }
    }

    let record = metadata::BuildRecord {
        build_id: build_id.clone(),
        fingerprint,
        revision,
        extracted_at: metadata::now()?,
        server: server_exe.display().to_string(),
        client: client.map(|path| path.display().to_string()),
    };
    let bytes = record.write(&target)?;
    rows.push(Row::new(Mark::Ok, metadata::FILE, "1").note(crate::ui::bytes(bytes as u64)));

    ui.rows(&rows);
    ui.line(&format!("written to {}", target.display()));
    Ok(true)
}

/// Find the server executable to read, and the buildid naming its output.
///
/// A fetched build takes its buildid from its directory name. An executable
/// named directly takes it from `--build`, and falls back to the app manifest
/// `SteamCMD` left beside it. Every branch validates the buildid the same way,
/// because it becomes a directory name the same way and `Path::join` would
/// take an absolute one as the whole path.
fn locate_server(
    root: &DevRoot,
    build: Option<&str>,
    server: Option<&Path>,
) -> Result<(PathBuf, String)> {
    let Some(path) = server else {
        let build_id = root.build_id(build)?;
        let dir = root.build_dir(&build_id)?;
        return Ok((dir.join("enshrouded_server.exe"), build_id));
    };
    if let Some(named) = build {
        crate::root::check_build_id(named)?;
        return Ok((path.to_path_buf(), named.to_string()));
    }
    let install = path.parent().unwrap_or(Path::new("."));
    match crate::root::build_id_from_manifest(install, crate::root::APP_ID) {
        Ok(from_manifest) => Ok((path.to_path_buf(), from_manifest)),
        Err(err) => bail!(
            "{err:#}. Pass --build <buildid> to name the extraction directory for {}.",
            path.display()
        ),
    }
}

/// Write one dump and describe it as a result row.
fn write(target: &Path, name: &str, body: &str) -> Result<Row> {
    let path = target.join(name);
    std::fs::write(&path, body).with_context(|| format!("writing {}", path.display()))?;
    let lines = body.matches(EOL).count();
    Ok(Row::new(Mark::Ok, name, lines.to_string()).note(crate::ui::bytes(body.len() as u64)))
}

/// Print the extractions this root holds.
fn list(root: &DevRoot, ui: &Ui) -> bool {
    let dir = root.schema_dir();
    let Ok(entries) = std::fs::read_dir(&dir) else {
        ui.section("schema");
        ui.line(&format!("no extractions under {}", dir.display()));
        return true;
    };
    let mut names: Vec<String> = entries
        .filter_map(std::result::Result::ok)
        .filter(|entry| entry.path().is_dir())
        .map(|entry| entry.file_name().to_string_lossy().into_owned())
        .collect();
    names.sort();
    ui.section("schema");
    if names.is_empty() {
        ui.line(&format!("no extractions under {}", dir.display()));
        return true;
    }
    let rows: Vec<Row> = names
        .iter()
        .map(|name| {
            let extraction = dir.join(name);
            let present = OUTPUTS
                .iter()
                .filter(|file| extraction.join(file).is_file())
                .count();
            let note = match metadata::BuildRecord::read(&extraction) {
                Ok(Some(record)) => record.summary(),
                Ok(None) => format!("no {}", metadata::FILE),
                Err(err) => format!("{}: {err}", metadata::FILE),
            };
            Row::new(Mark::Note, name, format!("{present} / {}", OUTPUTS.len())).note(note)
        })
        .collect();
    ui.rows(&rows);
    true
}

/// One field line, shared by the schema dump and the UI event dump.
fn field_line(out: &mut String, field: &descriptor::Field) {
    let type_name = field
        .type_name
        .as_deref()
        .or(field.type_short.as_deref())
        .unwrap_or("None");
    let size = field
        .type_size
        .map_or_else(|| "None".to_string(), |size| size.to_string());
    let _ = writeln_crlf(
        out,
        &format!(
            "    +{:#06x}  {:<44} : {type_name}  [{size}]",
            field.offset, field.name
        ),
    );
}

/// One enumerator line.
fn enum_line(out: &mut String, entry: &descriptor::Enumerator) {
    let _ = writeln_crlf(out, &format!("    ={:<8} {}", entry.value, entry.name));
}

/// Append a line with the dump's line ending.
fn writeln_crlf(out: &mut String, line: &str) -> std::fmt::Result {
    write!(out, "{line}{EOL}")
}

/// The full type schema, sorted by qualified name.
fn schema_dump(image: &Image, descriptors: &[descriptor::Descriptor]) -> String {
    let mut selected: Vec<&descriptor::Descriptor> = descriptors
        .iter()
        .filter(|entry| entry.full.starts_with("keen::"))
        .collect();
    selected.sort_by(|a, b| a.full.cmp(&b.full));
    let mut out = String::with_capacity(selected.len() * 256);
    for entry in selected {
        let _ = writeln_crlf(
            &mut out,
            &format!(
                "{}  @{:#x} size={:#x} align={} nfields={} flags={:#x} hash={:#018x}",
                entry.full,
                entry.base,
                entry.size,
                entry.align,
                entry.members,
                entry.flags,
                entry.hash
            ),
        );
        emit_members(&mut out, image, entry);
        let _ = writeln_crlf(&mut out, "");
    }
    out
}

/// The fields or the enumerators of one descriptor.
fn emit_members(out: &mut String, image: &Image, entry: &descriptor::Descriptor) {
    if entry.is_enum() {
        for value in descriptor::enumerators(image, entry) {
            enum_line(out, &value);
        }
    } else {
        for field in descriptor::fields(image, entry) {
            field_line(out, &field);
        }
    }
}

/// Every descriptor the engine registered with the entity system, in file
/// order, with the three raw words a signature check compares.
fn descriptor_table(descriptors: &[descriptor::Descriptor]) -> String {
    let mut out = String::new();
    for entry in descriptors {
        let Some(dotted) = entry.dotted.as_deref() else {
            continue;
        };
        if !dotted.starts_with("ecs.") {
            continue;
        }
        let _ = writeln_crlf(
            &mut out,
            &format!(
                "{:08X}\t{dotted}\t{}\t{}\t{:016X}\t{:016X}\t{:016X}",
                entry.offset + 0x40,
                entry.short,
                entry.full,
                entry.size_word,
                entry.count_word,
                entry.hash
            ),
        );
    }
    out
}

/// Whether a bare type name belongs in the UI event dump.
///
/// Three shapes qualify: a name starting with `Ui`, a name carrying `Ui` and
/// ending in `Event`, and a name carrying `HudScreen`. A name that merely holds
/// `Ui` in the middle, such as `PlayerSkillsUi`, is a component rather than a
/// surface a mod raises.
fn is_ui_surface(bare: &str) -> bool {
    bare.starts_with("Ui")
        || bare.contains("HudScreen")
        || (bare.contains("Ui") && bare.ends_with("Event"))
}

/// The UI surfaces a server-side mod can reach, with their field layouts.
fn ui_events(image: &Image, descriptors: &[descriptor::Descriptor]) -> String {
    const PREFIX: &str = "keen::ecs::";
    let mut selected: Vec<&descriptor::Descriptor> = descriptors
        .iter()
        .filter(|entry| entry.full.strip_prefix(PREFIX).is_some_and(is_ui_surface))
        .collect();
    selected.sort_by(|a, b| a.full.cmp(&b.full));
    let mut out = String::new();
    for entry in selected {
        let _ = writeln_crlf(&mut out, &entry.full);
        emit_members(&mut out, image, entry);
        let _ = writeln_crlf(&mut out, "");
    }
    out
}

/// The game session message registry.
fn proto_dump(image: &Image) -> String {
    let messages = proto::walk(image);
    let mut out = String::new();
    for message in &messages {
        let _ = writeln_crlf(
            &mut out,
            &format!(
                "{:<36} size={:#07x} nfields={}",
                message.name, message.size, message.declared_fields
            ),
        );
        for field in &message.fields {
            let _ = writeln_crlf(
                &mut out,
                &format!(
                    "      {:<26} type={:<12} off={:#07x} cap={:#x}",
                    field.name, field.wire_type, field.offset, field.capacity
                ),
            );
        }
    }
    let _ = writeln_crlf(&mut out, "");
    let _ = writeln_crlf(&mut out, &format!("[{} messages]", messages.len()));
    out
}

/// Every printable run in the image, at its file offset.
fn string_table(image: &Image) -> String {
    let runs = strings::scan(image.bytes());
    let mut out = String::with_capacity(runs.len() * 48);
    for run in runs {
        let _ = write!(&mut out, "{:08X}\t", run.offset);
        out.extend(run.text.iter().map(|byte| *byte as char));
        out.push_str(EOL);
    }
    out
}

/// Every program record, with the component sets each one touches.
fn program_table(image: &Image) -> String {
    let mut out = String::new();
    let _ = writeln_crlf(
        &mut out,
        &format!(
            "file_off\tname\tentry_va\t{}",
            program::SLOT_COLUMNS.join("\t")
        ),
    );
    for record in program::walk(image) {
        let cells: Vec<String> = record.slots.iter().map(|slot| slot.join(",")).collect();
        let _ = writeln_crlf(
            &mut out,
            &format!(
                "{:08X}\t{}\t{:#x}\t{}",
                record.offset,
                record.name,
                record.entry,
                cells.join("\t")
            ),
        );
    }
    out
}

/// Resolve a buildid the caller typed against the extractions on disk.
///
/// An exact directory name wins. Otherwise a prefix that matches one directory
/// resolves, and a prefix matching several is refused by name.
///
/// # Errors
///
/// Returns an error when nothing matches or when the prefix is ambiguous.
pub fn resolve_extraction(dir: &Path, wanted: &str) -> Result<PathBuf> {
    let exact = dir.join(wanted);
    if exact.is_dir() {
        return Ok(exact);
    }
    let entries = std::fs::read_dir(dir).with_context(|| format!("reading {}", dir.display()))?;
    let mut matches: Vec<PathBuf> = entries
        .filter_map(std::result::Result::ok)
        .map(|entry| entry.path())
        .filter(|path| {
            path.is_dir()
                && path
                    .file_name()
                    .and_then(|name| name.to_str())
                    .is_some_and(|name| name.starts_with(wanted))
        })
        .collect();
    matches.sort();
    match matches.len() {
        0 => bail!(
            "no extraction named {wanted} under {}. Run `cargo xtask schema list` to see what is there.",
            dir.display()
        ),
        1 => Ok(matches.remove(0)),
        _ => {
            let names: Vec<String> = matches
                .iter()
                .filter_map(|path| path.file_name())
                .map(|name| name.to_string_lossy().into_owned())
                .collect();
            bail!("{wanted} matches several extractions: {}", names.join(", "))
        }
    }
}

#[cfg(test)]
mod tests {
    use super::{is_ui_surface, locate_server};
    use crate::root::DevRoot;
    use crate::testutil::TestDir;

    /// `--build` beside `--server` becomes the extraction directory name, and
    /// `Path::join` takes an absolute argument as the whole path. Every spelling
    /// that would leave the cache is refused before any join.
    #[test]
    fn an_escaping_build_beside_server_is_refused() {
        let dir = TestDir::new("locate-escape");
        let root = DevRoot::resolve(Some(dir.path())).expect("a sandbox is an ordinary root");
        let exe = dir.write("elsewhere/enshrouded_server.exe", b"MZ");
        let library = dir
            .path()
            .join("fake")
            .join("SteamLibrary")
            .join("steamapps")
            .join("common")
            .join("Enshrouded");
        let absolute = library.to_string_lossy().into_owned();
        let cases: Vec<String> = vec![
            absolute,
            r"..\..\escaped".to_string(),
            "../../escaped".to_string(),
            ".fetching".to_string(),
        ];
        for build in &cases {
            let outcome = locate_server(&root, Some(build), Some(&exe));
            assert!(
                outcome.is_err(),
                "--build {build:?} beside --server must be refused"
            );
        }
        let (path, id) = locate_server(&root, Some("23178631"), Some(&exe))
            .expect("a plain buildid beside --server is fine");
        assert_eq!(path, exe);
        assert_eq!(id, "23178631");
    }

    /// A manifest beside the executable is an operator-editable file, so the
    /// buildid it carries is held to the same rule as a typed one.
    #[test]
    fn a_manifest_buildid_that_escapes_is_refused_beside_server() {
        let dir = TestDir::new("locate-manifest");
        let root = DevRoot::resolve(Some(dir.path())).expect("a sandbox is an ordinary root");
        let exe = dir.write("copy/enshrouded_server.exe", b"MZ");
        dir.write(
            "copy/steamapps/appmanifest_2278520.acf",
            br#""AppState"
{
	"buildid"		"..\..\manifest-escape"
}
"#,
        );
        let err = locate_server(&root, None, Some(&exe)).expect_err("the manifest buildid escapes");
        assert!(format!("{err:#}").contains("not usable"), "{err:#}");
    }

    #[test]
    fn the_ui_surface_rule_keeps_events_and_drops_components() {
        let cases: &[(&str, bool)] = &[
            ("UiNegativeFeedbackEvent", true),
            ("UiWorldEvent", true),
            ("UiInteractable", true),
            ("UiOffsets", true),
            ("UiOverlayType", true),
            ("OpenHudScreenEvent", true),
            ("KnowledgeUiWorldEvent", true),
            ("TriggerKnowledgeUiEvent", true),
            ("PathGridDebugUiCategory", false),
            ("PathGridDebugUiState", false),
            ("PlayerSkillsUi", false),
            ("Inventory", false),
            ("CraftRecipeEvent", false),
        ];
        for (name, want) in cases {
            assert_eq!(is_ui_surface(name), *want, "name {name}");
        }
    }
}
