[package]
name = "xtask"
description = "Repository automation for Ember."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
publish = false

[dependencies]
anyhow.workspace = true
clap.workspace = true
comfy-table.workspace = true
ember-kfc.workspace = true
goblin.workspace = true
owo-colors.workspace = true
serde.workspace = true
serde_json.workspace = true
time.workspace = true
which.workspace = true

[target.'cfg(windows)'.dependencies]
windows-link.workspace = true

[dev-dependencies]
pulldown-cmark.workspace = true
tempfile.workspace = true
toml.workspace = true

[lints]
workspace = true
